export const DASHBOARD_TONE_OPTIONS = [
  { value: "OCEAN", label: "Ocean Blue", swatch: "from-sky-500 to-blue-600" },
  { value: "SUNSET", label: "Sunset Orange", swatch: "from-amber-500 to-orange-600" },
  { value: "MINT", label: "Mint Green", swatch: "from-emerald-400 to-emerald-600" },
  { value: "CYAN_WAVE", label: "Cyan Wave", swatch: "from-cyan-500 to-sky-600" },
  { value: "CANDY", label: "Candy Pop", swatch: "from-fuchsia-500 to-pink-600" },
  { value: "FIRE", label: "Fire Red", swatch: "from-rose-500 to-red-600" },
  { value: "PLUM", label: "Plum Dream", swatch: "from-violet-500 to-purple-700" },
  { value: "LIME", label: "Lime Burst", swatch: "from-lime-500 to-green-700" },
  { value: "GOLD", label: "Gold Rush", swatch: "from-amber-400 to-orange-600" },
  { value: "TEAL", label: "Teal Pulse", swatch: "from-teal-400 to-cyan-600" },
  { value: "INDIGO", label: "Indigo Night", swatch: "from-indigo-500 to-blue-700" },
  { value: "CHERRY", label: "Cherry Soda", swatch: "from-pink-500 to-rose-600" },
] as const;

export const DEFAULT_DASHBOARD_TONE = "OCEAN";
export const DASHBOARD_TONE_VALUES = DASHBOARD_TONE_OPTIONS.map((option) => option.value) as [
  (typeof DASHBOARD_TONE_OPTIONS)[number]["value"],
  ...(typeof DASHBOARD_TONE_OPTIONS)[number]["value"][],
];

export const DASHBOARD_TONES = {
  OCEAN: {
    frame: "border-sky-300/30 bg-gradient-to-br from-sky-500 to-blue-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/14",
      "border-white/30 bg-white/18",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/10",
    ],
  },
  SUNSET: {
    frame: "border-amber-300/30 bg-gradient-to-br from-amber-500 to-orange-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/20",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/17",
      "border-white/30 bg-white/10",
    ],
  },
  MINT: {
    frame: "border-emerald-300/30 bg-gradient-to-br from-emerald-400 to-emerald-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/19",
      "border-white/30 bg-white/11",
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/09",
    ],
  },
  CYAN_WAVE: {
    frame: "border-cyan-300/30 bg-gradient-to-br from-cyan-500 to-sky-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/13",
      "border-white/30 bg-white/18",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/10",
    ],
  },
  CANDY: {
    frame: "border-fuchsia-300/30 bg-gradient-to-br from-fuchsia-500 to-pink-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/20",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/10",
    ],
  },
  FIRE: {
    frame: "border-rose-300/30 bg-gradient-to-br from-rose-500 to-red-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/18",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/10",
    ],
  },
  PLUM: {
    frame: "border-violet-300/30 bg-gradient-to-br from-violet-500 to-purple-700",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/21",
      "border-white/30 bg-white/13",
      "border-white/30 bg-white/18",
      "border-white/30 bg-white/10",
    ],
  },
  LIME: {
    frame: "border-lime-300/30 bg-gradient-to-br from-lime-500 to-green-700",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/14",
      "border-white/30 bg-white/20",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/17",
      "border-white/30 bg-white/10",
    ],
  },
  GOLD: {
    frame: "border-yellow-200/35 bg-gradient-to-br from-amber-400 to-orange-600",
    primary: "border-white/35 bg-white/20",
    soft: "border-white/30 bg-white/14",
    chip: "border-white/35 bg-black/25 text-white",
    heading: "text-white/85",
    title: "text-white",
    body: "text-white/95",
    muted: "text-white/75",
    queue: [
      "border-white/35 bg-white/16",
      "border-white/35 bg-white/22",
      "border-white/35 bg-white/13",
      "border-white/35 bg-white/18",
      "border-white/35 bg-white/11",
    ],
  },
  TEAL: {
    frame: "border-teal-300/30 bg-gradient-to-br from-teal-400 to-cyan-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/14",
      "border-white/30 bg-white/19",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/10",
    ],
  },
  INDIGO: {
    frame: "border-indigo-300/30 bg-gradient-to-br from-indigo-500 to-blue-700",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/14",
      "border-white/30 bg-white/18",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/10",
    ],
  },
  CHERRY: {
    frame: "border-pink-300/30 bg-gradient-to-br from-pink-500 to-rose-600",
    primary: "border-white/30 bg-white/16",
    soft: "border-white/25 bg-white/12",
    chip: "border-white/30 bg-black/25 text-white",
    heading: "text-white/80",
    title: "text-white",
    body: "text-white/90",
    muted: "text-white/75",
    queue: [
      "border-white/30 bg-white/15",
      "border-white/30 bg-white/20",
      "border-white/30 bg-white/12",
      "border-white/30 bg-white/16",
      "border-white/30 bg-white/10",
    ],
  },
} as const;

export function getDashboardTone(tone: string | null | undefined) {
  if (!tone) return DASHBOARD_TONES[DEFAULT_DASHBOARD_TONE];
  return DASHBOARD_TONES[tone as keyof typeof DASHBOARD_TONES] ?? DASHBOARD_TONES[DEFAULT_DASHBOARD_TONE];
}
